import type {
  SoilTestBooking,
  SoilReport,
  Payment,
} from '@farmhith/types';

export const mockBookings: SoilTestBooking[] = [
  {
    id: 'stb-101',
    farmerId: 'farmer-001', farmerName: 'Ramesh Kumar',
    labId: 'lab-001', labName: 'AgroScience Soil Lab',
    status: 'PENDING',
    cropType: 'Wheat',
    landParcelDetails: '3.5 acres, Ludhiana',
    collectionDate: '2026-04-14',
    amountPaid: 1200,
    reportConsentToMitra: true,
    createdAt: '2026-04-11T09:00:00Z',
  },
  {
    id: 'stb-102',
    farmerId: 'farmer-002', farmerName: 'Sukhwinder Singh',
    labId: 'lab-001', labName: 'AgroScience Soil Lab',
    status: 'ACCEPTED',
    cropType: 'Rice',
    landParcelDetails: '4.0 acres, Ludhiana',
    collectionDate: '2026-04-13',
    amountPaid: 1200,
    reportConsentToMitra: false,
    createdAt: '2026-04-10T14:00:00Z',
  },
  {
    id: 'stb-103',
    farmerId: 'farmer-003', farmerName: 'Balwant Kaur',
    labId: 'lab-001', labName: 'AgroScience Soil Lab',
    status: 'IN_PROGRESS',
    cropType: 'Maize',
    landParcelDetails: '2.0 acres, Moga',
    collectionDate: '2026-04-12',
    amountPaid: 1200,
    reportConsentToMitra: true,
    createdAt: '2026-04-09T10:00:00Z',
  },
  {
    id: 'stb-104',
    farmerId: 'farmer-004', farmerName: 'Harjit Dhaliwal',
    labId: 'lab-001', labName: 'AgroScience Soil Lab',
    status: 'COMPLETED',
    cropType: 'Wheat',
    landParcelDetails: '6.5 acres, Jalandhar',
    collectionDate: '2026-04-08',
    amountPaid: 1200,
    reportConsentToMitra: true,
    createdAt: '2026-04-05T09:00:00Z',
    report: {
      id: 'rep-101',
      bookingId: 'stb-104',
      reportUrl: '#',
      testParameters: { ph: 7.1, nitrogen: 260, phosphorus: 35, potassium: 210, moisture: 18 },
      technicianNotes: 'Nitrogen slightly low. Recommend DAP application.',
      uploadedAt: '2026-04-09T11:00:00Z',
    },
  },
  {
    id: 'stb-105',
    farmerId: 'farmer-005', farmerName: 'Gurwinder Brar',
    labId: 'lab-001', labName: 'AgroScience Soil Lab',
    status: 'CANCELLED',
    cropType: 'Sugarcane',
    landParcelDetails: '5.0 acres, Hoshiarpur',
    collectionDate: '2026-04-06',
    amountPaid: 0,
    reportConsentToMitra: false,
    createdAt: '2026-04-04T08:00:00Z',
  },
];

export const mockPayments: Payment[] = [
  { id: 'pay-101', payerUserId: 'farmer-001', payerName: 'Ramesh Kumar', payeeUserId: 'lab-001', payeeName: 'AgroScience Soil Lab', grossAmount: 1200, platformCommission: 60, netPayout: 1140, serviceType: 'SOIL_TEST', serviceRefId: 'stb-104', status: 'SETTLED', createdAt: '2026-04-09T12:00:00Z' },
  { id: 'pay-102', payerUserId: 'farmer-002', payerName: 'Sukhwinder Singh', payeeUserId: 'lab-001', payeeName: 'AgroScience Soil Lab', grossAmount: 1200, platformCommission: 60, netPayout: 1140, serviceType: 'SOIL_TEST', serviceRefId: 'stb-102', status: 'CAPTURED', createdAt: '2026-04-10T14:00:00Z' },
];
